import importlib.util
import subprocess
import sys
import textwrap
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def test_generate_registry_docs_writes_expected_registry(tmp_path: Path) -> None:
    module = load_script_module("generate_registry_docs")
    output = tmp_path / "docs" / "generated" / "REGISTRY.md"

    content = module.write_registry(output=output)

    assert output.read_text(encoding="utf-8") == content
    assert "script_lifecycle_lab" in content
    assert "echo_attachments" not in content
    assert "echo_script" not in content
    assert "render_test" not in content
    assert "codec" in content
    assert "file" in content
    assert "http" in content
    assert "Generated by:" in content


def test_generate_registry_docs_check_passes_when_current(tmp_path: Path) -> None:
    module = load_script_module("generate_registry_docs")
    output = tmp_path / "REGISTRY.md"
    module.write_registry(output=output)

    assert module.check_registry(output=output) is True


def test_generate_registry_docs_check_fails_when_stale(tmp_path: Path) -> None:
    module = load_script_module("generate_registry_docs")
    output = tmp_path / "REGISTRY.md"
    module.write_registry(output=output)
    output.write_text("stale\n", encoding="utf-8")

    assert module.check_registry(output=output) is False


def test_generate_registry_docs_does_not_import_runtime_code(tmp_path: Path) -> None:
    module = load_script_module("generate_registry_docs")
    agents_root = tmp_path / "agents"
    capabilities_root = tmp_path / "capabilities"
    write_minimal_prompt_agent(agents_root / "demo_agent")
    write_minimal_capability(capabilities_root / "demo_capability")
    (capabilities_root / "demo_capability" / "__init__.py").write_text(
        "raise RuntimeError('runtime imported')\n",
        encoding="utf-8",
    )

    content = module.generate_registry_markdown(agents_root=agents_root, capabilities_root=capabilities_root)

    assert "demo_agent" in content
    assert "demo_capability" in content


def test_generate_registry_docs_handles_missing_optional_fields(tmp_path: Path) -> None:
    module = load_script_module("generate_registry_docs")
    agents_root = tmp_path / "agents"
    capabilities_root = tmp_path / "capabilities"
    write_minimal_prompt_agent(agents_root / "minimal_agent")
    write_minimal_capability(capabilities_root / "minimal_capability")

    content = module.generate_registry_markdown(agents_root=agents_root, capabilities_root=capabilities_root)

    assert "| minimal_agent | Minimal Agent | prompt | default |  |  |  |  |" in content
    assert "| minimal_capability | Minimal Capability | echo | /minimal |  | text |  |" in content


def test_generate_registry_docs_cli_check_detects_mismatch(tmp_path: Path) -> None:
    output = tmp_path / "REGISTRY.md"
    output.write_text("stale\n", encoding="utf-8")

    result = subprocess.run(
        [sys.executable, str(ROOT / "scripts" / "generate_registry_docs.py"), "--check", "--output", str(output)],
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=False,
    )

    assert result.returncode != 0
    assert "is out of date" in result.stdout


def load_script_module(name: str):
    path = ROOT / "scripts" / f"{name}.py"
    spec = importlib.util.spec_from_file_location(f"test_{name}", path)
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def write_minimal_prompt_agent(agent_dir: Path) -> None:
    agent_dir.mkdir(parents=True)
    agent_dir.joinpath("agent.yaml").write_text(
        textwrap.dedent(
            f"""
            id: {agent_dir.name}
            name: Minimal Agent
            type: prompt
            actions:
              - id: default
                label: Chat
            """
        ).strip(),
        encoding="utf-8",
    )


def write_minimal_capability(capability_dir: Path) -> None:
    capability_dir.mkdir(parents=True)
    capability_dir.joinpath("capability.yaml").write_text(
        textwrap.dedent(
            f"""
            id: {capability_dir.name}
            name: Minimal Capability
            methods:
              - id: echo
                output:
                  part_type: text
                  format: plain
            commands:
              - name: /minimal
                method: echo
            """
        ).strip(),
        encoding="utf-8",
    )
