from __future__ import annotations

from collections.abc import AsyncIterator
from typing import Protocol

from ai_workbench.core.models.schema import (
    ChatChunk, ChatRequest, ChatResult, EmbeddingPurpose, EmbeddingResult, ModelProfile,
    ModelStatus, RerankResult, SiglipResult, Tower, VisionResult, AudioOutput, ASRParameters, TranscriptionResult, ImageOutput,
)


class InferenceAdapter(Protocol):
    async def chat(self, profile: ModelProfile, request: ChatRequest) -> ChatResult: ...
    def chat_stream(self, profile: ModelProfile, request: ChatRequest) -> AsyncIterator[ChatChunk]: ...
    async def embed(self, profile: ModelProfile, texts: list[str], dimensions: int | None, *, purpose: EmbeddingPurpose = "document") -> EmbeddingResult: ...
    async def rerank(self, profile: ModelProfile, query: str, documents: list[str]) -> RerankResult: ...
    async def image_embed(self, profile: ModelProfile, tower: Tower, inputs: list[str]) -> SiglipResult: ...
    async def vision(self, profile: ModelProfile, images: list[str], thresholds: dict[str, float]) -> VisionResult: ...
    async def speech(self, profile: ModelProfile, text: str, voice: str, speed: float, response_format: str, language: str | None) -> AudioOutput: ...
    async def transcribe(self, profile: ModelProfile, reference: str, options: ASRParameters) -> TranscriptionResult: ...
    async def close(self) -> None: ...


class ProviderAdapter(InferenceAdapter, Protocol):
    async def models(self) -> list[str]: ...


class LocalAdapter(InferenceAdapter, Protocol):
    async def process_image(self, profile: ModelProfile, image: ImageOutput, options: dict) -> ImageOutput: ...
    async def health(self, profile: ModelProfile) -> ModelStatus: ...
    async def load(self, profile: ModelProfile, *, explicit: bool = False) -> ModelStatus: ...
    async def unload(self, profile: ModelProfile) -> ModelStatus: ...
    def snapshot(self, profile: ModelProfile) -> ModelStatus: ...
