from __future__ import annotations

from collections.abc import AsyncIterator
from typing import Protocol

from ai_workbench.core.models.schema import (
    ChatChunk, ChatRequest, ChatResult, EmbeddingResult, ModelProfile,
    ModelStatus, RerankResult, VisionResult, AudioOutput,
)


class ProviderAdapter(Protocol):
    async def models(self) -> list[str]: ...
    async def health(self, profile: ModelProfile) -> ModelStatus: ...
    async def load(self, profile: ModelProfile) -> ModelStatus: ...
    async def unload(self, profile: ModelProfile) -> ModelStatus: ...
    async def chat(self, profile: ModelProfile, request: ChatRequest) -> ChatResult: ...
    def chat_stream(self, profile: ModelProfile, request: ChatRequest) -> AsyncIterator[ChatChunk]: ...
    async def embed(self, profile: ModelProfile, texts: list[str], dimensions: int | None) -> EmbeddingResult: ...
    async def rerank(self, profile: ModelProfile, query: str, documents: list[str]) -> RerankResult: ...
    async def image_embed(self, profile: ModelProfile, images: list[str]) -> EmbeddingResult: ...
    async def vision(self, profile: ModelProfile, images: list[str]) -> VisionResult: ...
    async def speech(self, profile: ModelProfile, text: str, voice: str, speed: float, response_format: str, language: str | None) -> AudioOutput: ...
    async def close(self) -> None: ...
